/**
 * Generates dist/sw.js after the bundle exists.
 *
 * Why generated rather than hand-written in public/: Vite content-hashes
 * assets/index-*.js, so any precache list written by hand is wrong the moment
 * anything changes -- and a service worker with a stale list is worse than no
 * service worker, because it caches half an app and serves it forever.
 *
 * The worker itself is deliberately small. The app is ALREADY fully offline:
 * every byte of training data lives in localStorage and nothing here talks to a
 * server. All the worker removes is the need for a network to *load* the shell,
 * which is the difference between a wake-up routine happening and not.
 *
 * Run by `npm run build`. No Workbox, no dependencies.
 */

import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))
const dist = join(root, 'dist')

/** Every emitted file, as a path relative to dist/, with '/' separators. */
function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name)
    return statSync(full).isDirectory() ? walk(full) : [full]
  })
}

let files
try {
  files = walk(dist)
} catch {
  console.error('buildSW: no dist/ — run `vite build` first.')
  process.exit(1)
}

const shell = files
  .map((f) => relative(dist, f).split('\\').join('/'))
  // sw.js must never cache itself: the browser has to be able to fetch a fresh
  // copy to discover that an update exists at all.
  .filter((name) => name !== 'sw.js')
  .sort()

// Cache name from the content of everything precached, so a new build always
// lands in a new cache and the old one is dropped on activate. Hashing content
// rather than filenames covers the un-hashed files too (index.html, the icons,
// the manifest), which is exactly where a stale cache would otherwise hide.
const hash = createHash('sha256')
for (const name of shell) hash.update(name).update(readFileSync(join(dist, name)))
// This file's own bytes go into the hash as well. Change the worker's logic
// without changing the app and the cache name has to move too -- otherwise the
// new worker inherits the old cache, including anything the old logic put there
// that it should not have.
hash.update(readFileSync(fileURLToPath(import.meta.url)))
const version = hash.digest('hex').slice(0, 12)

const sw = `/* Generated by scripts/buildSW.mjs. Do not edit -- rebuild instead. */
const CACHE = 'trainer-${version}'
const SHELL = ${JSON.stringify(shell, null, 2).split('\n').join('\n')}
const INDEX = new URL('index.html', self.location.href).href

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      // { cache: 'reload' } so the precache is filled from the network rather
      // than from whatever the HTTP cache is still holding. Precaching a stale
      // copy of index.html would defeat the entire point of the version hash.
      .then((cache) => cache.addAll(
        SHELL.map((f) => new Request(new URL(f, self.location.href).href, { cache: 'reload' })),
      ))
      .then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((names) => Promise.all(names.filter((n) => n !== CACHE).map((n) => caches.delete(n))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const req = event.request
  if (req.method !== 'GET') return

  // Anything off this origin -- an Instagram link from a reel-sourced exercise,
  // say -- is none of our business. Let the browser do exactly what it would
  // have done without a worker installed.
  if (new URL(req.url).origin !== self.location.origin) return

  // Every route is the same single-page shell.
  if (req.mode === 'navigate') {
    event.respondWith(caches.match(INDEX).then((hit) => hit || fetch(req)))
    return
  }

  event.respondWith(
    caches.match(req).then((hit) => {
      if (hit) return hit
      return fetch(req).then((res) => {
        // Never store an HTML answer under a non-HTML URL.
        //
        // A single-page host answers "no such file" with the app shell and a
        // 200 -- vite preview does, and so do most static hosts. Caching that
        // under /assets/index-abc123.js poisons the cache permanently: every
        // later load gets HTML where the browser demanded a module, and the app
        // goes blank with a MIME type error until someone clears storage by
        // hand. This is the exact failure the precache list exists to avoid, so
        // it does not get to sneak back in through the runtime path.
        const isHtml = (res.headers.get('content-type') || '').includes('text/html')
        if (res.ok && res.type === 'basic' && !isHtml) {
          const copy = res.clone()
          caches.open(CACHE).then((cache) => cache.put(req, copy))
        }
        return res
      })
    }),
  )
})
`

writeFileSync(join(dist, 'sw.js'), sw)
console.log(`buildSW: dist/sw.js — cache trainer-${version}, ${shell.length} files precached`)
