import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.tsx'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)

/**
 * The service worker exists for one reason: so opening the app on a phone with
 * no signal, at 6am, still works. Everything else is already offline -- the
 * data lives in localStorage and never leaves the device.
 *
 * dist/sw.js is generated by scripts/buildSW.mjs after the bundle is hashed,
 * so it is only present in a production build.
 */
if (import.meta.env.PROD && 'serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register(`${import.meta.env.BASE_URL}sw.js`).catch((err) => {
      // Not fatal: without a worker the app still runs, it just needs the network
      // to load. Never let this take the app down with it.
      console.warn('Service worker registration failed:', err)
    })
  })

  // A new worker calls skipWaiting(), so it takes over as soon as it activates.
  // Reload once when that happens -- otherwise a phone can sit on a months-old
  // build forever.
  //
  // Two guards, both needed. `hadController` is false on the very first visit,
  // where the worker claims a page that is already running the newest build:
  // reloading there would be a pointless flash on first open. `reloading` stops
  // a repeat from turning into a loop.
  const hadController = Boolean(navigator.serviceWorker.controller)
  let reloading = false
  navigator.serviceWorker.addEventListener('controllerchange', () => {
    if (!hadController || reloading) return
    reloading = true
    window.location.reload()
  })
}
